application: google-voice-webhook
version: 1
runtime: nodejs20
instance_class: F1

handlers:
- url: /_ah/mail/.+
  script: google-voice-webhook.js

inbound_services:
- mail

automatic_scaling:
  max_instances: 1
  min_instances: 0
